version: "3.8"

services:
  app:
    build: .
    image: flaskapp:latest
    container_name: flaskapp_container
    command: python app.py
    ports: 
      - 5001:5000
    depends_on: 
      - db

  db:
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    container_name: db_container
    volumes:
      - ./data/db:/var/lib/postgres/data  

